global:
  scrape_interval: 15s # How often Prometheus scrapes the data

scrape_configs:
  - job_name: "docker"
    static_configs:
      - targets:
          - "nginx:80" # Target Nginx (replace with your service names)
          - "postgres:5432" # Target PostgreSQL (replace with your service names)
          - "mongo:27017" # Target MongoDB
          - "redis:6379" # Target Redis
          - "rabbitmq:5672" # Target RabbitMQ
          - "elasticsearch:9200" # Target Elasticsearch
          - "prometheus:9090" # Prometheus metrics (itself)

# Optional: Configure more advanced scraping rules or alerts if needed
